### ISSUE TITLE
Richer user information

### ISSUE THREAD

**Issue by QuantumNightmare** [serilog/serilog-sinks-raygun#22]
Hi, I work at Raygun where we have been starting to use this sink more.

We would like to be able to log more user information to the extent of what can be placed on the RaygunIdentifierMessage model. The Raygun Serilog sink could look for the "UserInfo" key (with an option to provide a custom key) in the event properties which could be set to a whole RaygunIdentifierMessage model. The presence of this key would cause the UserName key to be ignored.

This may be considered a breaking change if users are already happen to be using a "UserInfo" key.

I'm happy to work on a PR for this when I get time. Let me know what you think of this.

**Comment by nblumhardt** [comment]
Hi! Sounds very interesting.

Another possibility might be to opt in, initially, through something like a `mapUserInfo: "<propertyName>"` sink configuration setting, or some means of pulling the required properties from a `LogEvent` via callback?

I'm not up to date on the Raygun side of it; in Serilog logs it's unusual for payload properties to have first-class meaning for sinks, but not completely unheard-of 👍

**Comment by QuantumNightmare** [comment]
Great idea with making it opt-in, that could avoid this from being a potential breaking change. I'll see how it goes when I get around to making the PR.

**Comment by QuantumNightmare** [comment]
I've created a PR for this here: https://github.com/serilog/serilog-sinks-raygun/pull/25

I had thought of two approaches to take:

1. Add a new option for each and every property value available on RaygunIdentifierMessage (6 in total). Each which would be null by default to make them all opt-in. This however would bloat the RaygunSink constructor quite a bit, and it would be trickier to explain the conflict/duplication between the existing user-name option and the new first-name/full-name/identifier options. (the existing user-name option is related to the identifier property of RaygunIdentifierMEssage, but it's worded as though it's the full-name value).
2. Add a single property which you can set as a RaygunIdentifierMessage instance to hold all those values that you want. This gets serialized by serilog (by using the ToString method by default) which we then deserialize in the Raygun sink to resolve the RaygunIdentifierMessage section of the Raygun payload.

The second option seems a bit brittle due to relying on the format of the ToString method of RaygunIdentifierMessage. However I like the usability of that approach much better than the first approach, and so I've gone with the latter. We'll just make sure the ToString implementation always supports this sink. You can see a simple example of using this approach in the readme additions.
