### ISSUE TITLE
Deduplicate custom data

### ISSUE THREAD

**Issue by QuantumNightmare** [serilog/serilog-sinks-raygun#23]
The Raygun Serilog sink allows you to specify certain Raygun specific properties such as user name, tags and application version. The sink will cause these to be populated into the appropriate places in the Raygun payload model, but, it also leaves those values in the custom data section which doubles up the values.

This ticket proposes that anything that gets placed into Raygun payload specific properties, also gets removed from the custom data dictionary. The thought is to remove the data duplication which will make the reports display a little cleaner in Raygun. The payload size is shortened a little too, though this isn't as much of a concern except for the case where there may be a lot of Tag content.

This may be considered a breaking change though.

Let me know if you have any thoughts on this idea. I'm happy to work on a PR.

**Comment by nblumhardt** [comment]
Sounds great! Thanks for digging into it 👍 

If the change is breaking, we just need to increment the major version in the `.csproj` file; you're probably placed better than I am to judge the likelihood of downstream breakage - worth keeping the package evolving when possible.

**Comment by QuantumNightmare** [comment]
Implemented here: https://github.com/serilog/serilog-sinks-raygun/pull/26

We've had a think about this and do not consider this to be a breaking change.

**Comment by nblumhardt** [comment]
Merged 👍
