### ISSUE TITLE
Update Serilog.Sinks.Raygun with unsigned Raygun assembly

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-raygun#3]
@wwwlicious in https://github.com/serilog/serilog/issues/744

> The Serilog.Sinks.Raygun package is currently using the sn raygun assembly which is causing two packages I have in a project that depend on Raygun to have a contest to see who can cause the most conflicts.
> 
> Propose this is either updated to use the non-strong named assembly or a new package is created that doesn't use strong named dependencies so that it can 'play well with others' :)

**Comment by nblumhardt** [comment]
Yuck - thanks for the heads-up. Dropping strong naming from this package could break others, so probably not an option. Creating an additional `.Unsigned` package from the build seems like the "right" thing to do, but it'll be fiddly work. Forking and hacking at it is probably the fastest way forward :-)

**Comment by wwwlicious** [comment]
No problem, internally I just modified the package to change the dependency, bumped the version and stuck it on an internal nuget feed but it was annoying my CI server today so I thought I'd log it. 

Sorry for the hassle!

**Comment by nblumhardt** [comment]
Closing this one as I think it's stale, the new build has moved forward to a new Raygun integration.
