### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by aignas** [serilog/serilog-sinks-raygun#4]
I am not sure about the implementation of this sink, but since Raygun4Net supports .NET Core, I thought maybe it is doable in this project as well.

The support was brought in with the following PR:
https://github.com/MindscapeHQ/raygun4net/pull/302

**Comment by mattruma** [comment]
This going to happen soon?

**Comment by nblumhardt** [comment]
If anyone can send a PR, this would be welcome 👍 

Most of the active Serilog sinks now support .NET Core; anyone interested in tackling this should take a look at the project/build structure in https://github.com/serilog/serilog-sinks-console as we've used this consistently elsewhere. Cheers!

**Comment by sirkirby** [comment]
@mattruma I have a PR up for this #12 which will support netcoreapp2.0 and netstandard2.0 targets using the mindscape AspNetCore package.
