### ISSUE TITLE
Update Serilog dependency

### ISSUE THREAD

**Issue by roberthardy** [serilog/serilog-sinks-raygun#5]
I experienced the following error when I tried to install the Serilog.Sinks.Raygun package:

`Unable to resolve dependencies. 'Serilog 2.2.1' is not compatible with 'Serilog.Sinks.Raygun 1.5.8 constraint: Serilog (>= 1.4.204 && < 2.0.0)'.`

Is it possible to update the dependency constraints in the nuspec?

**Comment by nblumhardt** [comment]
Thanks for the note @roberthardy; I've created a PR to remove the version constraint.

**Comment by nblumhardt** [comment]
The constraint has been removed, if you have any issues with package version 1.5.10 please let us know. Cheers!

**Comment by roberthardy** [comment]
Thanks @nblumhardt !
