### ISSUE TITLE
Redundant quotation marks included in the version string

### ISSUE THREAD

**Issue by roberthardy** [serilog/serilog-sinks-raygun#7]
I'm not sure whether this is a problem with my Serilog config but I have the following issue.

When the Serilog Raygun sink emits a log event it sets the `Version` property of the Raygun message details before sending the error message to Raygun. However, an unnecessary set of quote marks gets included in the version string (e.g. `"\"1.0.39\""`). When viewed in Raygun the error event looks like [this](http://i.imgur.com/UGO4ktT.png). This is incorrect with the result being that Raygun is unable to figure out which deployment the error belongs to. Seems to be related to the `ToString()` [this line](https://github.com/serilog/serilog-sinks-raygun/blob/87244f85c3a341e4b1a617f1d2088b32227da728/src/Serilog.Sinks.Raygun/Sinks/Raygun/RaygunSink.cs#L120).

**Comment by nblumhardt** [comment]
Hi, thanks for the report. Looks like it should be `ToString("l", null)`.

**Comment by roberthardy** [comment]
I've submitted pr #10

**Comment by nblumhardt** [comment]
Great - thanks! Build should be out of CI shortly 👍
