### ISSUE TITLE
LoggerConfiguration not referenced when using core 1.1.0

### ISSUE THREAD

**Issue by axelgunn** [serilog/serilog-sinks-raygun#9]
Everything is fine when in version netcoreapp1.0 but when upgrading to netcoreapp1.1 / NetCore.App 1.1.0, compilation fails with the message 
The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

and points to : Log.Logger = new **LoggerConfiguration()**

here are my project.json dependencies

    "dependencies": {
        "Microsoft.AspNet.WebApi.Core": "5.2.3",
        "Swashbuckle": "6.0.0-beta902",
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.Data.Services.Client": "5.8.2",
        "Microsoft.Extensions.Caching.Abstractions": "1.1.0",
        "Microsoft.Extensions.Caching.Memory": "1.1.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.Extensions.Logging": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0",
        "Microsoft.Extensions.Logging.Debug": "1.1.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
        "Microsoft.IdentityModel.Protocols": "2.1.2",
        "System.Spatial": "5.8.2",
        "Microsoft.NETCore.App": {
            "version": "1.1.0",
            "type": "platform"
        },
        "AutoMapper.Extensions.Microsoft.DependencyInjection": "1.2.0",
        "Microsoft.AspNetCore.Mvc.WebApiCompatShim": "1.1.0",
        "Microsoft.AspNetCore.Routing": "1.1.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
        "Mindscape.Raygun4Net.AspNetCore": "5.3.2",
        "Serilog": "2.4.0",
        "Serilog.Sinks.Literate": "2.1.0",
        "Serilog.Extensions.Logging": "1.4.0",
        "Serilog.Sinks.RollingFile": "3.3.0",
        "Serilog.Sinks.Seq": "3.2.0",
        "Serilog.Sinks.Raygun": "2.0.13"
    },

    "frameworks": {
        "netcoreapp1.1": {
            "imports": [
                "dotnet5.6",
                "dnxcore50",
                "portable-net45+win8",
                "net462"
            ]
        }
    },

**Comment by QuantumNightmare** [comment]
Apologies this issue was neglected. When I've seen that error message in the past, it's been due to needing to run `dotnet restore`. I'll close this off due to being out of date, but feel free to reopen or create a new issue if there are problems using the current version of this sink.
